### PR TITLE
Fetch more pages

### PR DESCRIPTION
**Pull request by LowbeerR**
First load is now fetching 4 pages, scroll is new fetching 3 pages

### CODE REVIEW

**Review by pilsnerfrajz — APPROVED** [review]
Looks good and seems to work! 

Would be nice to remove commented-out code and place "Error while loading..." in a `<p>` element instead of `<div>` before merging.

**Comment by LowbeerR** [comment]
Fixed your comment and the bug. (what i could see it does not happen anymore)

**Review by pontaberglund — APPROVED** [review]
Looks good. Everything seems to work for me.

**Review by pilsnerfrajz — APPROVED** [review]
Error seems to be fixed. Looks good now!

**Pull request merged**
