### PR TITLE
Add friends

### PR DESCRIPTION
**Pull request by LowbeerR**
New in this PR:

- Show/Hide User ID:
Users can now toggle the visibility of their ID with a button.
The button dynamically changes its label based on the current visibility status.

- Friend Requests Section:
Displays a section for incoming friend requests when there are pending requests.
Allows users to accept or decline friend requests individually.

- Add Friends:
Provides an input field for adding friends by entering their ID.
A custom message is displayed, if any, to provide additional context.

- Sent Requests Section:
Shows a section for sent friend requests, indicating users awaiting a response.
Users can cancel sent friend requests.

- Current Friends Section:
Displays a list of current friends with options to interact with each friend.
Users can navigate to a friend's profile or remove a friend from the list.

How to test:

Enter a user ID in the field and press Enter. If the ID is linked to a user a friend request will be sent and be visible as pending.
The user who got the request will see this as incoming friend request and choose to accept or decline. If declined the friend request is removed, aswell as the pending request. Otherwise you added each other as friends and can now check each others favorites.

TODO: 
- Styling
- Maybe add option to change nickname

### CODE REVIEW

**Comment by pilsnerfrajz** [comment]
### Suggestions
- Maybe we should add “Permission denied” if you try to access a friend's profile when not logged in instead of 404 
- Keep the headers uniform. Remove colon from “Waiting for answer from:”
- Don't mix capital letters as in “These are your Friends”

### Extra features later(?)
- Suggested friends. We could hard-code it to use our profiles

**Comment by Cactooz** [comment]
> ### Suggestions
> * Maybe we should add “Permission denied” if you try to access a friend's profile when not logged in instead of 404
> * Keep the headers uniform. Remove colon from “Waiting for answer from:”
I agree these would be great!

**Comment by pilsnerfrajz** [comment]
I'll address the spelling in a different PR. We will use Toastify to give feedback to the user instead.

**Comment by LowbeerR** [comment]
Should now give 403 in case id given after profile/ID is not a user on the app

**Review by pilsnerfrajz — APPROVED** [review]
Seems to work flawlessly!

**Pull request merged**
